name: Bug report
description: Create a bug report to help us improve Serenity Platform
title: "[Bug report]: <Short description of the bug>"
labels: waiting-for-check
assignees: VictorTomaili

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: confirmation
    attributes:
      label: Before submitting the bug report, please read and check the following items
      description: We need to ensure this is not a false positive bug report.
      options:
        - label: This isn't a feature request or a discussion topic (Please use discussions for that)
          required: true
        - label: I have searched open and closed issues for duplicates
          required: true
        - label: I am searched documents on the Serenity Platform website https://serenity.is/docs/
          required: true
        - label: I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
          required: true
        - label: I have do a search in the discussion and old issues https://github.com/serenity-is/Serenity/discussions
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen (included images if possible)?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-did-you-expect
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
      placeholder: Expectations!
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reporoduce?
      description: Also tell us, we can reproduce?
      placeholder: Tell us how we can reproduce!
      value: "Steps to reproduce the behavior!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: console
  - type: markdown
    attributes:
      value: |
        # Development environment details
  - type: input
    id: template-version
    attributes:
      label: Serene template version
      description: What is the current version of the serene template?
      placeholder: "1.0.0"
      value: "1.0.0"
  - type: input
    id: sergen-version
    attributes:
      label: Sergen version
      description: What is the current version of Sergen?
      placeholder: "1.0.0"
      value: "1.0.0"
  - type: input
    id: serenity-versions
    attributes:
      label: What Serenity Nuget Versions are you seeing the problem on?
      placeholder: Serenity Versions (separated by comma)
      value: "Serenity.Scripts 1.0.0, Serenity.Assets 1.0.0, Serenity.Net.Web 1.0.0..."
    validations:
      required: true
  - type: input
    id: code-editor
    attributes:
      label: Code editor
      description: What code editor are you using? And which version?
      placeholder: "Visual Studio XXXX, version 1.0.0"
      value: "Visual Studio XXXX, version 1.0.0"
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What is the current version of the operating system?
      placeholder: "Windows 11"
      value: "Windows 11"
  - type: input
    id: nodejs-version
    attributes:
      label: Node.js version
      description: What is the current version of Node.js?
      placeholder: "v1.0.0"
      value: "v1.0.0"
  - type: input
    id: typescript-version
    attributes:
      label: TypeScript version
      description: What is the current version of TypeScript?
      placeholder: "1.0.0"
      value: "1.0.0"
  - type: input
    id: database-type
    attributes:
      label: Database type and version
      description: What is the current type of database and version?
      placeholder: "Sql Server, version 1.0.0 or MySql, version 1.0.0"
      value: "Sql Server"
  - type: markdown
    attributes:
      value: |
        # Client details
  - type: input
    id: device
    attributes:
      label: What device are you seeing the problem on?
      placeholder: "Desktop, Laptop, Tablet, Phone, etc."
      value: "Desktop"
  - type: input
    id: device-os
    attributes:
      label: What operating system are you seeing the problem on?
      placeholder: "Windows, Mac, Linux, IOS, Android etc."
      value: "Windows"
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: input
    id: browser-version
    attributes:
      label: What version of the browser are you seeing the problem on?
      placeholder: Version number of the browser
      value: "1.0.0"
  - type: markdown
    attributes:
      value: |
        # Additional information
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any additional information you would like to add.
      placeholder: "Additional information"
      value: "Additional information"
