# Builds and test 
name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 7.29.0
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.14.2'
        cache: 'pnpm'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Dotnet Test
      run: dotnet test --no-build --verbosity normal
    - name: Javascript Test
      run: pnpm test
      working-directory: "src/Serenity.Scripts/corelib"
